on: [pull_request]

jobs:
  changed-dockerfiles:
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed Dockerfiles
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            */*/Dockerfile
      - name: Set Matrix
        id: set-matrix
        run: |
          # From a space separated list of files, split by space, then use the parent and grandparent dirs to get image and tag info
          MATRIX=$(echo ${{ steps.changed-files.outputs.all_changed_files }} | jq -Rr 'split(" ") | map(split("/")) | map({"image": .[-3], "tag": .[-2]}) | @json')
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
  build-docker:
    needs: changed-dockerfiles
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include: ${{ fromJSON(needs.changed-dockerfiles.outputs.matrix) }}
    steps:
      - id: echo-jobs
        run: |
          echo "Image name is ${{ matrix.image }}"
          echo "Image tag is ${{ matrix.tag }}"
      - id: cavatica-login
        uses: docker/login-action@v2
        with:
          registry: pgc-images.sbgenomics.com
          username: ${{ secrets.CAVATICA_USERNAME }}
          password: ${{ secrets.CAVATICA_TOKEN }}
      - id: test-build
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.image }}/${{ matrix.tag }}
          tags: pgc-images.sbgenomics.com/${{ secrets.CAVATICA_USERNAME }}/${{ matrix.image }}:${{ matrix.tag }}
