on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed Dockerfiles
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            */*/Dockerfile
      - name: Set Matrix
        id: set-matrix
        run: |
          MATRIX=$(echo ${{ steps.changed-files.outputs.all_changed_files }} | jq -sR 'split("\n") | map(select(. != "")) | map(split(" ")) | flatten | map(split("/")) | map({"image": .[-3], "tag": .[-2]}) | {"include": .} | @json' | sed -r 's/^"|"$//g' | tr -s /) 
          echo $MATRIX
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
  job2:
    needs: build
    runs-on: ubuntu-22.04
    strategy:
      matrix: ${{ fromJSON(needs.build.outputs.matrix) }}
    steps:
      - id: echo-jobs
        run: |
          echo "Image name is ${{ matrix.image }}"
          echo "Image tag is ${{ matrix.tag }}"
        
